/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

    THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
    KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
    PURPOSE.

Module Name:

    IsrDpc.c

Abstract:

    Contains routines related to interrupt and dpc handling.

Environment:

    Kernel mode

--*/

#include "precomp.h"

#include "IsrDpc.tmh"

NTSTATUS
PLxInterruptCreate(
    IN PDEVICE_EXTENSION DevExt
    )
/*++
Routine Description:

    Configure and create the WDFINTERRUPT object.
    This routine is called by EvtDeviceAdd callback.

Arguments:

    DevExt      Pointer to our DEVICE_EXTENSION

Return Value:

    NTSTATUS code

--*/
{
    NTSTATUS                    status;
    WDF_INTERRUPT_CONFIG        InterruptConfig;

    WDF_INTERRUPT_CONFIG_INIT( &InterruptConfig,
                               PLxEvtInterruptIsr,
                               PLxEvtInterruptDpc );

    InterruptConfig.EvtInterruptEnable  = PLxEvtInterruptEnable;
    InterruptConfig.EvtInterruptDisable = PLxEvtInterruptDisable;

    // JOHNR: Enable testing of the DpcForIsr Synchronization
    InterruptConfig.AutomaticSerialization = TRUE;

    //
    // Unlike WDM, framework driver should create interrupt object in EvtDeviceAdd and
    // let the framework do the resource parsing and registration of ISR with the kernel.
    // Framework connects the interrupt after invoking the EvtDeviceD0Entry callback
    // and disconnect before invoking EvtDeviceD0Exit. EvtInterruptEnable is called after
    // the interrupt interrupt is connected and EvtInterruptDisable before the interrupt is
    // disconnected.
    //
    status = WdfInterruptCreate( DevExt->Device,
                                 &InterruptConfig,
                                 WDF_NO_OBJECT_ATTRIBUTES,
                                 &DevExt->Interrupt );

    if( !NT_SUCCESS(status) ) {
        TraceEvents(TRACE_LEVEL_ERROR, DBG_PNP,
                    "WdfInterruptCreate failed: %!STATUS!", status);
    }

    return status;
}

BOOLEAN
PLxEvtInterruptIsr(
    IN WDFINTERRUPT Interrupt,
    IN ULONG        MessageID
    )
/*++
Routine Description:

    Interrupt handler for this driver. Called at DIRQL level when the
    device or another device sharing the same interrupt line asserts
    the interrupt. The driver first checks the device to make sure whether
    this interrupt is generated by its device and if so clear the interrupt
    register to disable further generation of interrupts and queue a
    DPC to do other I/O work related to interrupt - such as reading
    the device memory, starting a DMA transaction, coping it to
    the request buffer and completing the request, etc.

Arguments:

    Interupt   - Handle to WDFINTERRUPT Object for this device.
    MessageID  - MSI message ID (always 0 in this configuration)

Return Value:

     TRUE   --  This device generated the interrupt.
     FALSE  --  This device did not generated this interrupt.

--*/
{
	UNREFERENCED_PARAMETER(Interrupt);
	UNREFERENCED_PARAMETER(MessageID);
	/*
    PDEVICE_EXTENSION   devExt;
    BOOLEAN             isRecognized = FALSE;

    union {
		INTERRUPT_FLAG bits;
        UCHAR   uchar;
    } interruptStatus;

    UNREFERENCED_PARAMETER(MessageID);

    TraceEvents(TRACE_LEVEL_INFORMATION, DBG_INTERRUPT,
                "--> PLxInterruptHandler");

    devExt  = PLxGetDeviceContext(WdfInterruptGetDevice(Interrupt));

    //
    // Read the Interrupt CSR register (INTCSR)
    //
	interruptStatus.uchar = READ_PORT_UCHAR((PUCHAR)&devExt->Regs->Interrupt_Flag);//read interrupt flag

	WRITE_PORT_UCHAR((PUCHAR)&devExt->Regs->Interrupt_Clear, interruptStatus.uchar);//write interrupt clear

	if (interruptStatus.bits.IRQ0 || interruptStatus.bits.IRQ1 || interruptStatus.bits.IRQ2 || interruptStatus.bits.IRQ3) {
		isRecognized = TRUE;
	}
				
	if (isRecognized) {
		WdfInterruptQueueDpcForIsr(devExt->Interrupt);
	}
	
    TraceEvents(TRACE_LEVEL_INFORMATION, DBG_INTERRUPT,
                "<-- PLxInterruptHandler %02x", interruptStatus.uchar);

    return isRecognized;
	*/
	return FALSE;
}

_Use_decl_annotations_
VOID
PLxEvtInterruptDpc(
    WDFINTERRUPT Interrupt,
    WDFOBJECT    Device
    )
/*++

Routine Description:

    DPC callback for ISR. Please note that on a multiprocessor system,
    you could have more than one DPCs running simulataneously on
    multiple processors. So if you are accesing any global resources
    make sure to synchrnonize the accesses with a spinlock.

Arguments:

    Interupt  - Handle to WDFINTERRUPT Object for this device.
    Device    - WDFDEVICE object passed to InterruptCreate

Return Value:

--*/
{
    //NTSTATUS            status;
    PDEVICE_EXTENSION   devExt;

    UNREFERENCED_PARAMETER(Device);


    TraceEvents(TRACE_LEVEL_INFORMATION, DBG_DPC, "--> EvtInterruptDpc");

    devExt  = PLxGetDeviceContext(WdfInterruptGetDevice(Interrupt));

    //
    // Acquire this device's InterruptSpinLock.
    //
    WdfInterruptAcquireLock( Interrupt );

    //
    // Release our interrupt spinlock
    //
    WdfInterruptReleaseLock( Interrupt );

    TraceEvents(TRACE_LEVEL_INFORMATION, DBG_DPC, "<-- EvtInterruptDpc");

    return;
}

NTSTATUS
PLxEvtInterruptEnable(
    IN WDFINTERRUPT Interrupt,
    IN WDFDEVICE    Device
    )
/*++

Routine Description:

    Called by the framework at DIRQL immediately after registering the ISR with the kernel
    by calling IoConnectInterrupt.

Return Value:

    NTSTATUS
--*/
{
	UNREFERENCED_PARAMETER(Interrupt);
	UNREFERENCED_PARAMETER(Device);

	/*
    PDEVICE_EXTENSION  devExt;

    union {
        EXTERNAL_INTERRUPT_CONTROL   bits;
        USHORT     ushort;
    } interruptControl;

    TraceEvents(TRACE_LEVEL_INFORMATION, DBG_INTERRUPT,
                "PLxEvtInterruptEnable: Interrupt 0x%p, Device 0x%p\n",
                Interrupt, Device);

    devExt  = PLxGetDeviceContext(WdfInterruptGetDevice(Interrupt));

	WRITE_PORT_ULONG((PULONG)&devExt->Regs->VirtualRegisterAddress, 0x0002);

	//interruptControl.bits.IRQ0_InterruptEnable = TRUE;    //0 : Masked			1 : Enable
	//interruptControl.bits.IRQ0_InterruptType = TRUE;      //0 : Level			1 : Edge
	//interruptControl.bits.IRQ0_InterruptPriority = TRUE;  //0 : Low				1 : High
	//interruptControl.bits.IRQ0_Polarity = FALSE;          //0 : Active - Low	1 : Active - High
	interruptControl.ushort = 0x7777;

	WRITE_PORT_USHORT((PUSHORT)&devExt->Regs->VirtualRegisterData, interruptControl.ushort);
	*/

    return STATUS_SUCCESS;
}

NTSTATUS
PLxEvtInterruptDisable(
    IN WDFINTERRUPT Interrupt,
    IN WDFDEVICE    Device
    )
/*++

Routine Description:

    Called by the framework at DIRQL before Deregistering the ISR with the kernel
    by calling IoDisconnectInterrupt.

Return Value:

    NTSTATUS
--*/
{
    PDEVICE_EXTENSION  devExt;

    //union {
    //    INT_CSR   bits;
    //    ULONG     ulong;
    //} intCSR;

    TraceEvents(TRACE_LEVEL_INFORMATION, DBG_INTERRUPT,
                "PLxEvtInterruptDisable: Interrupt 0x%p, Device 0x%p\n",
                Interrupt, Device);

    devExt  = PLxGetDeviceContext(WdfInterruptGetDevice(Interrupt));

	//WRITE_PORT_USHORT((PUSHORT)(devExt->RegsBase + 0x0A), 0x0000);

	//WRITE_PORT_ULONG((PULONG)&devExt->Regs->VirtualRegisterAddress, 0x0002);

	//WRITE_PORT_USHORT((PUSHORT)&devExt->Regs->VirtualRegisterData, 0x0000);

    return STATUS_SUCCESS;
}
